RAM.WMSCustomerPortal/WMSCustomerPortal.Web/Controllers/WarehouseController.cs
using System;
using System.Web.Mvc;
using System.Collections;
using System.Collections.Generic;
using WMSCustomerPortal.Business;
using WMSCustomerPortal.Business.Models;
using WMSCustomerPortal.Models.Common;
using WMSCustomerPortal.Models;
using WMSCustomerPortal.Models.Entities;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;
using RAM.Utilities.Common;


namespace WMSCustomerPortal.Web.Controllers {
    [Authorize(Roles = "Backdoor, Warehouse")]
    public class WarehouseController : BaseController {

        WMSCustomerPortal.Business.WarehouseService _service;

        private WMSCustomerPortal.Business.WarehouseService DataService {
            get {
                if (_service == null) {
                    _service = new WMSCustomerPortal.Business.WarehouseService();
                }
                return _service;
            }
        }

        /// <summary>
        /// Return the default warehouse list view 
        /// </summary>
        /// <returns></returns>
        public ActionResult WarehouseList() {
            // return View("WarehouseList");
            return View();
        }
        public ActionResult ReturnReceipt()
        {
            return View();
        }

        public ActionResult ReturnReceiptList(string ramOrderNumber)
        {
            var returnReceiptList = new ReturnMasterItem { RAMOrderNumber = ramOrderNumber };
            return View(returnReceiptList);
        }
        public ActionResult ReturnIGD()
        {           
            return View();
        }

        /// <summary>
        /// Returns alist of all the items for the warehouse 
        /// </summary>
        /// <param name="param"></param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public JsonResult GetWarehouseList(JQueryDataTableParamModel param, string filter) {
            int principalID = 0;
            try {
                principalID = Session.GetDataFromSession<int>("WMSSession.PrincipalID");

            }
            catch {
                principalID = 0;
            }

            //TODO: Dates that are to be filtered
            System.DateTime dtFrom = new DateTime();
            System.DateTime dtTo = new DateTime();
            dtFrom = DateTime.Now.AddYears(-2);
            dtTo = DateTime.Now;

            //TODO: Purcase Order Reference
            string poRef = "";

            var sessionData = DataService.GetAllInboundMasterFilter(principalID, poRef, dtFrom, dtTo); //.GetAllCustomers(principalID);

            var data = new {
                sEcho = param.sEcho,
                iTotalRecords = sessionData.Count,
                iTotalDisplayRecords = sessionData.Count,
                aaData = sessionData
            };

            // Test serialization using overriden method
            var response = Json(data, JsonRequestBehavior.AllowGet);

            return response;
        }

        /// <summary>
        /// Return a dynamic list of inbound line items according to the master id specified
        /// </summary>
        /// <param name="param"></param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public JsonResult GetWarehouseLineItemsList(JQueryDataTableParamModel param, int masterId) {

            var sessionData = DataService.GetInboundLineItemsList(masterId);

            var data = new {
                sEcho = param.sEcho,
                iTotalRecords = sessionData.Count,
                iTotalDisplayRecords = sessionData.Count,
                aaData = sessionData,
                Result = "SUCCESS"
            };

            // Test serialization using overriden method
            var response = Json(data, JsonRequestBehavior.AllowGet);

            return response;
        }

        /// <summary>
        /// Return a dynamic list of inbound line items according to the master id specified
        /// </summary>
        /// <param name="param"></param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public JsonResult GetWarehouseIGDList(JQueryDataTableParamModel param, int lineItemID) {

            var sessionData = DataService.GetIGDStagingList(lineItemID);

            var data = new {
                sEcho = param.sEcho,
                iTotalRecords = sessionData.Count,
                iTotalDisplayRecords = sessionData.Count,
                aaData = sessionData
            };

            // Test serialization using overriden method
            var response = Json(data, JsonRequestBehavior.AllowGet);

            return response;
        }

        /// <summary>
        /// Deletes an igd line item
        /// </summary>
        /// <param name="inboundMasterLineItemID"></param>
        /// <returns></returns>
        public JsonResult DeleteIGD(int igdStagingID) {

            string eventTerminal = this.TerminalID;
            string eventUser = this.LoggedOnUser;

            //we would like to delete this record 

            bool success = DataService.DeleteIGDStaging(igdStagingID, eventTerminal, eventUser);


            if (success) {
                var response = new {
                    SaveResponse = new BaseSaveResponse { Details = "Record Deleted." },
                    Result = "SUCCESS"
                };
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else {
                var response = new {
                    SaveResponse = new BaseSaveResponse { Details = "Record Not Deleted." },
                    Result = "FAILURE"
                };
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Submits all the igd records which have been created to WMS for a specified lineItemID 
        /// </summary>
        /// <param name="lineItemIDForSubmission"></param>
        /// <returns></returns>
        public JsonResult SubmitSingleToWMS(int InboundMasterLineItemID) {
            string eventTerminal = this.TerminalID;
            string eventUser = this.LoggedOnUser;

            int principalID = Session.GetDataFromSession<int>("WMSSession.PrincipalID");
           

           //bool success = DataService.SubmitAllIGDStagingLineItem(InboundMasterLineItemID, eventTerminal, eventUser, principalID);

           bool success = DataService.SubmitSingleIGDStagingLineItem(InboundMasterLineItemID, eventTerminal, eventUser, principalID);

            if (success) {
                var response = new {
                    SaveResponse = new BaseSaveResponse { Details = "Records Submitted." },
                    Result = "SUCCESS"
                };

                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else {
                var response = new {
                    SaveResponse = new BaseSaveResponse { Details = "Records Not All Submitted." },
                    Result = "FAILURE"
                };

                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult CommitIGDItems(int inboundMasterLineID) //pass through the master id
        {
            bool retVal = true;

            int principalID = Session.GetDataFromSession<int>("WMSSession.PrincipalID");

            if (mIGDLineItems == null)
            {
                mIGDLineItems = new Dictionary<int, SaveIGDLine>();
            }

            try
            {
                mIGDLineItems = Session.GetDataFromSession<Dictionary<int, SaveIGDLine>>("WMSSession.TempIGDLine");
            }
            catch (Exception ex)
            {
                // we cannot get to the dictionary ... do nothing because we dont have any lines possibly
            }
            List<SaveIGDLine> lineItems = this.ReorderLineItems(mIGDLineItems);
            //loop through each of the line items and construct the lineitems and save
            foreach (SaveIGDLine lineitem in mIGDLineItems.Values)
            {
                IGDStaging igdLi = new IGDStaging();

               igdLi.IGDStagingID = lineitem.IGDStagingID;
               if ((lineitem.InboundMasterLineItemID == 0) || (lineitem.InboundMasterLineItemID == null))
               {
                   igdLi.InboundMasterLineItemID = inboundMasterLineID;
               }
               else
               {
                   igdLi.InboundMasterLineItemID = lineitem.InboundMasterLineItemID;
               }
               //igdLi.InboundMasterLineItemID = lineitem.InboundMasterLineItemID;
               igdLi.MoveRef = lineitem.MoveRef;
               igdLi.ReceivedQuantity = lineitem.ReceivedQuantity;
               igdLi.SubmittedToWMS = lineitem.SubmittedToWMS;
                //ok ... now we save 
               //int saveRecord = SaveIGDItem(igdLi, principalID);
               int saveRecord = SavePartialIGDItem(igdLi, principalID);
                if (saveRecord < 1)
                {
                    //there is an issue ...
                    retVal = false;

                   
                  
                }
                else
                {
                    retVal = true;
                }
            }

            //lets reload the session variables with the new values as saved in the database
            
            //after a sve etc ... lets get the values correct from the db

                PrepopulateSessionItems(inboundMasterLineID);

            if (retVal)
            {
                var response = new
                {
                    SaveResponse = new BaseSaveResponse { Details = "Records Commited." },
                    Result = "SUCCESS"
                };

                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var response = new
                {
                    SaveResponse = new BaseSaveResponse { Details = "Records Not All Commited." },

RAM.WMSCustomerPortal/WMSCustomerPortal.Web/Views/Warehouse/ReturnReceipt.cshtml
@{
    ViewBag.Title = ">Return Receipt Main";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 class="page-header">Return Receipt Main</h3>

<input type="button" id="btnTest" value="Reset Table" onclick="ResetDataTable()" style="display:none;" />

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Results
            </div>            
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper" style="overflow:scroll;">
                    <table class="table table-bordered table-hover table-striped" id="dataTableReports">
                        <thead>
                            <tr>            
                                <th style="width:70px;">Return Reference Number</th>
                                <th style="width:90px;">Outbound Order Number</th>
                                <th style="width:300px;">Sender Name</th>
                                <th style="width:100px;">Date Created</th>
                                <th style="width:50px;"></th>
                            </tr>
                        </thead>
                    </table>
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<style>
    .modal-dialog {
        width: 750px;
    }

    form label.error {
        color: crimson;
    }

</style>

<!-- DataTables CSS -->
<link href="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
<!-- DataTables Responsive CSS -->
<link href="~/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- jQuery UI CSS -->
<link href="~/Content/jquery.ui.autocomplete.css" rel="stylesheet" />
<link href="~/Content/Spinner.css" rel="stylesheet" />
<link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<!-- DataTables JavaScript -->
<script src="~/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/Scripts/BestUpper/jquery.bestupper.min.js"></script>

<script>
    var oReportTable = null;

    $(document).ready(function () {

        $("input.form-control").bestupper();

        var $loading = $('#loading');
        $(document).ajaxStart(function () {
            $loading.show();
        }).ajaxStop(function () {
            $loading.hide();
        });

        GetReturnReceipt();

        WireAdditionalActions();
    });

    function ResetDataTable() {

        var Browser = detectIE();
        if (Browser == false) {

            var data = new Object();
            data.sEcho = null;
            data.iTotalRecords = 0;
            data.iTotalDisplayRecords = 0;
            data.aaData = null;

            oReportTable.destroy();

            oReportTable = $('#dataTableReports').DataTable({
                "order": [[2, "asc"]],
                "lengthMenu": [[20, 30, 40, -1], [20, 30, 40, "All"]],
                "bJQueryUI": true,
                "bServerSide": false,
                "bProcessing": true,
                "data": data
            });

            GetReturnReceipt();
        }
        else {
            //location.reload(true);
            window.location.reload();
        }
    }

    function detectIE() {
        var ua = window.navigator.userAgent;

        var msie = ua.indexOf('MSIE ');
        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        var trident = ua.indexOf('Trident/');
        if (trident > 0) {
            // IE 11 => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        var edge = ua.indexOf('Edge/');
        if (edge > 0) {
            // Edge (IE 12+) => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        return false;
    }

    function GetReturnReceipt() {

        if (oReportTable != null) {
            oReportTable.destroy();
        }

        oReportTable = $('#dataTableReports').DataTable({
            "order": [[0, "asc"]],
            "lengthMenu": [[20, 30, 40, -1], [20, 30, 40, "All"]],
            "bJQueryUI": true,
            "bServerSide": false,
            "sAjaxSource": '@Url.Action("GetReturnReceiptList", "Returns")',
            "bProcessing": true,
            "fnServerData": function (sSource, parameters, fnCallback) {
                parameters.push({ "name": "filter", "value": "" });

                $.getJSON(sSource, parameters, function (json) {
                    fnCallback(json)
                })
                .done(function () { })
                .fail(function (jqXHR, textStatus, errorThrown) {
                    swal("ERROR: " + errorThrown);
                    console.log("ERROR: " + errorThrown);
                    console.log("RESPONSE TEXT: " + jqXHR.responseText);
                })
                .always(function () { });
            },
            "columns": [
                            { "data": "ReturnReferenceNumber" },
                            { "data": "RAMOrderNumber" },
                            { "data": "CustomerName" },
                            { "data": "EventDate" },
                            {
                                "targets": -1,
                                "data": null,
                                "defaultContent": "<button viewLineItems class='btn btn-primary btn-xs'>View Line Items</button>"
                            }
            ]
        });
    }


    function PopulateLineItems(dRow) {
        //fills in the values of the form for the igd screen
        $('#txtProductStagingID').val(dRow.ProductStagingID);
        $('#txtReceivedInWarehouseQuantity').val(dRow.ReceivedInWarehouseQuantity);
        $('#txtExpectedQuantity').val(dRow.ExpectedQuantity);
        $('#txtEANCode').val(dRow.EANCode);
        $('#txtProdCode').val(dRow.ProdCode);

        //also save the InboundMasterLineItemID - we will be using this for a new record
        $('#txtInboundLineItemID').val(dRow.InboundMasterLineItemID);

        //lets populate the grid with the IGD items
        //PopulateWarehouseIGDData(dRow.InboundMasterLineItemID);
    }

    function WireAdditionalActions() {

        $('#dataTableReports tbody').on('click', 'button[viewLineItems]', function () {
           var row = oReportTable.row($(this).parents('tr'));
           ViewLineItems(row.data());
        });

        //set the listener to redirect us to the new view
        $('#dataTableReports tbody').on('click', 'button[viewLineItems]', function () {
            //var row = oInboundMasterTable.row($(this).parents('tr'));
            var row = oReportTable.row($(this).parents('tr'));
            //PopulateWarehouseLineItemsData(row.data());

            var idx = row.data().RAMOrderNumber;          
            var ref = '@Url.Action("ReturnReceiptList", "Warehouse", new { ramOrderNumber = "__id__" })';
            var ref2 = "";
            ref2 = ref.replace("__id__", idx);
            location.href = ref2;
        });
    }

    function ViewLineItems(d) {

        $('#modalViewLineItems').modal({
            keyboard: false
        });
    }

</script>

RAM.WMSCustomerPortal/WMSCustomerPortal.Web/Views/Warehouse/ReturnReceiptList.cshtml
@{
    ViewBag.Title = "Warehouse Return Line Items";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@model WMSCustomerPortal.Models.Common.ReturnMasterItem

<h3 class="page-header">Warehouse Return Line Items</h3>

@* Main Panel *@
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Results               
                <div>
                    @Html.ActionLink("Back to Return Receipt", "ReturnReceipt", "Warehouse")
                </div>
            </div>
            @*Page Headers*@
            <div class="panel-body">
                <form role="form" id="frmEditWarehouse" onsubmit="return false;">
                    @Html.HiddenFor(model => model.RAMOrderNumber, new { id = "hdnRAMOrderNumber" })
                    <div class="row">                       
                        <div class="col-xs-4 col-sm-6">
                            <div class="form-group">
                                <label>Return Reference Number</label>
                                <input class="form-control" placeholder="Return Reference Number" id="txtReturnReferenceNumber" name="txtReturnReferenceNumber" disabled>
                            </div>
                            <div class="form-group">
                                <label>Sender Name</label>
                                <input class="form-control" placeholder="Sender Name" id="txtSenderName" name="txtSenderName" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4 col-sm-6">
                            <div class="form-group">
                                <label>Outbound Order Number</label>
                                <input class="form-control" placeholder="Outbound Order Number" id="txtOutboundOrderNumber" name="txtOutboundOrderNumber" disabled>
                            </div>
                        </div>
                        <div class="col-xs-4 col-sm-6">
                            <div class="form-group">
                                <label>Return Waybill Number</label>
                                <input class="form-control" placeholder="Return Waybill Number" id="txtReturnWaybillNumber" name="txtReturnWaybillNumber">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            @*Page Header End*@
            @*Grid View*@
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="float:right;"></div>
                    <div class="dataTable_wrapper" style="overflow:scroll;">
                        <table class="table table-striped table-bordered table-hover" id="dataTableReturnLineItemList">
                            <thead>
                                <tr>
                                    <th>Product Code</th>
                                    <th>Long Description</th>
                                    <th>Short Description</th>
                                    <th>Expected Qty</th>
                                    <th>Received in WH Qty</th>
                                </tr>
                            </thead>                           
                        </table>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" id="btnSaveQty">Save</button>
                        </div>
                    </div>
                </div>
            </div>
            @*Grid View End*@       
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to Return Receipt", "ReturnReceipt", "Warehouse")
</div>

<style>
    .modal-dialog {
        width: 1000px;
    }  
</style>

<input id="hiddenAction" type="hidden" value="" />
<input id="hiddenPrincipalID" type="hidden" value="" />

<!-- DataTables CSS -->
<link href="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
<!-- DataTables Responsive CSS -->
<link href="~/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- jQuery UI CSS -->
<link href="~/Content/jquery.ui.autocomplete.css" rel="stylesheet" />
<link href="~/Content/Spinner.css" rel="stylesheet" />
<link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<!-- DataTables JavaScript -->
<script src="~/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
<script src="~/Scripts/Numeric/jquery.numeric.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/Scripts/BestUpper/jquery.bestupper.min.js"></script>

<script>

    //Initialize datatables
    var iReturnLineItemsTable = null;
    var mdlID2 = null;

    var simple_checkbox = function (data, type, full, meta) {
        var is_checked = data == true ? "checked" : "";
        return '<input disabled type="checkbox" class="checkbox" ' +
            is_checked + ' />';
    }

    $(document).ready(function () {

        $("input.form-control").bestupper();
        //alert("Document is Ready");

        //get the RAM Order Number from the model
        var mdlID = $("#hdnRAMOrderNumber").val();
        mdlID2 = mdlID;
        var $loading = $('#loading');
        $(document).ajaxStart(function () {
            $loading.show();
        }).ajaxStop(function () {
            $loading.hide();
        });

        //Poulate master record
        PopulateReturnListMaster(mdlID);
    });

    //Begin population of Header
    function PopulateReturnListMaster(pRAMOrderNumber) {

        var parameters = JSON.stringify({
            RAMOrderNumber: pRAMOrderNumber
        });

        $.ajax({
            url: '@Url.Action("GetReturnReceiptLineItems", "Returns")',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: parameters,
            success: function (response) {

                CompleteFormData(response);
                //console.log(response);
             },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                swal({
                    title: 'Error',
                    text: 'There was an error:' + errorThrown,
                    type: 'error',
                    confirmButtonText: 'OK',
                    confirmButtonColor: '#D42E12'
                });
            }
        });
    }

    //Populate header and line detail
    function CompleteFormData(returns) {       

        $('#txtReturnReferenceNumber').val(returns.Data.ReturnReferenceNumber);
        $('#txtSenderName').val(returns.Data.CustomerName);
        $('#txtOutboundOrderNumber').val(returns.Data.RAMOrderNumber);

        console.log(returns.Data.ReturnWaybillNumber);
        if (returns.Data.ReturnWaybillNumber != ''){

            $('#txtReturnWaybillNumber').val(returns.Data.ReturnWaybillNumber);
        }

        var lineItems = returns.Data.LineItems;
        console.log(lineItems);
        //Bind to grid
        //console.log(returns.Data.LineItems[0].ProdCode);
        iReturnLineItemsTable = $('#dataTableReturnLineItemList').DataTable({
            "order": [[0, "desc"]],
            "lengthMenu": [[20, 30, 40, -1], [20, 30, 40, "All"]],
            "data": lineItems,
            "columns": [

                { "data": "ProdCode" },
                { "data": "LongDesc" },
                { "data": "ShortDesc" },
                { "data": "Quantity" },
                {
                    "targets": -1,
                    "data": null,
                    "defaultContent": "<input id='qty'/>"
                }
            ]
        });        

        $('#btnSaveQty').click(function () {

            var quantity = 0;
            var receivedQTY = "";
            var message = "";
            var isValid = true;             

            //Validations before starting update
            iReturnLineItemsTable.rows().eq(0).each(function (index) {

                var row = iReturnLineItemsTable.row(index);
                var data = row.data();

                quantity = data.Quantity;
                receivedQTY = iReturnLineItemsTable.cell(index, 4).nodes().to$().find('input').val();
                currentReceivedQTY = data.ReceivedInWHQuantity;                

                //Validate the value to be less than or equal to original and numeric value
                if (receivedQTY > quantity || isNaN(receivedQTY) ) {
                   
                    isValid = false;
                    message = "Incorrect quantity!, Cannot exceed original quantity"
                }

                if (receivedQTY > (quantity - currentReceivedQTY)){

                    isValid = false;
                    message = "The Received quantity is higher than expected, please recount and enter the correct quantity received"
                }
            });   
            
            if (isValid == true) {

                UpdateReturnLine();
            } else {                
                swal({
                    title: message,
                    type: "warning",
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "OK"
                })              
            }
        });
    }

    var rowCount = 0;

    //Begin update of coloumns
    function UpdateReturnLine() {

        rowCount = iReturnLineItemsTable.rows().length;
        var lineItems = [];

        iReturnLineItemsTable.rows().eq(0).each(function (index) {

            var row = iReturnLineItemsTable.row(index);
            var data = row.data();

            var lineItemID = data.LineItemID;
            var prodCode = data.ProdCode;
            var quantity = data.Quantity; 
            var currentReceivedQTY = data.ReceivedInWHQuantity; 


            //Set existing values
            var receivedQTY = iReturnLineItemsTable.cell(index, 4).nodes().to$().find('input').val()
            if (receivedQTY == "" || receivedQTY == 0) {

                receivedQTY = currentReceivedQTY;
            }

            //Create object to pass to service
            var lines = new Object();

            lines.LineItemID = data.LineItemID;
            lines.Quantity = receivedQTY;
            lines.ReturnWaybill = $('#txtReturnWaybillNumber').val();

            lineItems.push(lines);
        });

        UpdateLineItem(lineItems);
    }   

    function UpdateLineItem(lineItem) {

        var parameters = JSON.stringify({
            lineItems: lineItem
        });

        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateReturnReceiptLine", "Returns")',
            data: parameters,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {

                swal({
                    title: "Saved",
                    type: "success",
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "OK",
                    closeOnConfirm: true
                },
                    function (isConfirm) {
                        if (isConfirm) {
                            document.location = 'ReturnReceipt';
                        }
                })              
            },            
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                swal({
                    title: 'Error',
                    text: 'There was an error:' + errorThrown,
                    type: 'error',
                    confirmButtonText: 'OK',
                    confirmButtonColor: '#D42E12'
                })
            }            
        });
    }

</script>
    